// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqupcygqxytbtvrpfjnh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxdXBjeWdxeHl0YnR2cnBmam5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMjU2MDAsImV4cCI6MjA3MDgwMTYwMH0.UsZ6vS_PtcfHxAYLQ6lYA_gJF7SI17n_rJJdraRk4wA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});